### ISSUE TITLE
can no longer login to fresh ec2 : key cannot be used for signing

### ISSUE THREAD

**Issue by yarikoptic** [ReproNim/reproman#563]
I believe such workflow was working fine before but no longer :-/

```
$> reproman create -t aws-ec2 my-nitrc-quick -b instance_type=t2.medium  -b key_name=my-nitrc      
2020-12-14 21:52:00,246 [INFO   ] Waiting for EC2 instance i-031cfd2f416c24ddc to start running... 
2020-12-14 21:52:45,842 [INFO   ] EC2 instance i-031cfd2f416c24ddc is running! 
2020-12-14 21:52:45,842 [INFO   ] Waiting for EC2 instance i-031cfd2f416c24ddc to complete initialization... 
2020-12-14 21:55:32,412 [INFO   ] EC2 instance i-031cfd2f416c24ddc initialized! 
2020-12-14 21:55:32,434 [INFO   ] Created the environment my-nitrc-quick 
(dev3) 1 44265.....................................:Mon 14 Dec 2020 09:55:32 PM EST:.
(git)lena:~/proj/repronim/reproman[master]git
$> reproman -l debug login my-nitrc-quick                                           
2020-12-14 21:58:09,526 [DEBUG  ] SSH connecting to ubuntu@3.227.208.24:22, authenticating with SSH config 
Exception: key cannot be used for signing
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/paramiko/transport.py", line 2109, in run
    handler(self.auth_handler, m)
  File "/usr/lib/python3/dist-packages/paramiko/auth_handler.py", line 298, in _parse_service_accept
    sig = self.private_key.sign_ssh_data(blob)
  File "/usr/lib/python3/dist-packages/paramiko/agent.py", line 418, in sign_ssh_data
    raise SSHException("key cannot be used for signing")
paramiko.ssh_exception.SSHException: key cannot be used for signing

Password for my-nitrc-quick: 
```

originally such an error message was seen in https://github.com/ReproNim/reproman/issues/480 but in connection to kerberos login.  But may be kerberos was a red-hairing and unrelated?

or may be it is because I decided to reuse prior key from another instance (provided `-b key_name`?

**Comment by yarikoptic** [comment]
I believe it was just that key_filename was `None`.
